create database capstone_1;
use capstone_1;
select * from capstone_1.brands;
select * from capstone_1.categories;
select * from capstone_1.customers;
select * from capstone_1.order_items;
select * from capstone_1.orders;
select * from capstone_1.products;
select * from capstone_1.staffs;
select * from capstone_1.stocks;
select * from capstone_1.stores;

-- Join orders, order_items, and products to display detailed line items.

select * from capstone_1.orders as a
inner join order_items as b on a.order_id=b.order_id
inner join products as c on b.product_id=c.product_id;

-- Write a query to group sales (total_price) by each store_id.

select s.store_id,sum(oi.total_price) as Total_price from capstone_1.stores as s
inner join orders as o on s.store_id = o.store_id
inner join order_items as oi on o.order_id = oi.order_id
group by s.store_id;

-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.

select product_name,sum(quantity) as total_qty_sold from capstone_1.order_items
group by product_name
order by total_qty_sold desc limit 5;

-- For each customer, return total orders placed, total items purchased, and total revenue.

select c.customer_id,concat(c.first_name,' ',c.last_name) as customer_name, count(distinct o.order_id) as total_orders,
sum(oi.quantity) as total_items_purchased,sum(oi.total_price) as total_revenue from capstone_1.customers as c
inner join orders as o on c.customer_id = o.customer_id
inner join order_items as oi on o.order_id = oi.order_id
group by c.customer_id,customer_name order by total_revenue desc;

-- Write a query to classify customers into spending brackets (e.g., low, medium, high).

select c.customer_id,sum(oi.total_price) as total_spent,
case 
when sum(oi.total_price) < 1000 then 'low'
when sum(oi.total_price) between 1000 and 5000 then 'medium'
else 'high'
end as spending_brackets from capstone_1.customers as c
inner join orders as o on c.customer_id = o.customer_id
inner join order_items as oi on o.order_id = oi.order_id
group by c.customer_id order by total_spent desc;

-- Analyze total revenue generated by each staff member based on their handled orders.

select s.staff_id,concat(s.first_name,' ',s.last_name) as staff_name,sum(oi.total_price) as total_revenue from capstone_1.staffs as s
inner join capstone_1.orders as o on s.staff_id = o.staff_id
inner join capstone_1.order_items as oi on o.order_id = oi.order_id
group by s.staff_id,staff_name
order by total_revenue desc;

-- Write a query to list products where stock quantity < 10 in any store.


select p.product_id,p.product_name,s.store_id,s.quantity from capstone_1.stocks as s
inner join capstone_1.products as p on p.product_id = s.product_id where s.quantity <10 order by s.quantity desc;


-- Create a table customer_segments that will be populated from Python ML results later.

create table customer_segments
(customer_id int, foreign key (customer_id) references Customers(customer_id),
recency int,
frequency int,
monetaryy decimal(10,2));


use capstone_1;
select * from rfm;







